fix gcc: assl.c:246: error: format not a string literal and no format arguments
format *is* a string literal but it was decided in a previous if statement to a
char *, so use snprintf(,,,"%s", prefix) instead of snprintf(,,,prefix);